### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by yanqswhu** [ai4ce/RealCity3D#1]
Thanks for your work!

I want to know if there are any plans to texture the models?

**Comment by simbaforrest** [comment]
Hi @Yannnnnnnnnnnn, we do not have any plan to include texture at this moment. Our focus is the geometric data. Texture data could be retrieved from satellite or aerial images by users using the geo-coordinates, but unfortunately, we do not have any of those and cannot share any of those without violating copyrights. 

I hope this answers your question.

**Comment by yanqswhu** [comment]
Thanks for your reply!
